app-description: Transaction Microservice API for managing transactions of Emezon
app-title: Transaction Management API
app-version: 1.0.0

server:
    port: ${PORT:8080}
spring:
    application:
        name: transaction
    datasource:
        driver-class-name: ${DB_DRIVER:org.h2.Driver}
        password: ${DB_PASS:root}
        url: ${DB_URL:jdbc:h2:mem:test-stock-db}
        username: ${DB_USER:root}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
                format_sql: false
        show-sql: false
    security:
        jwt:
            secret: ${JWT_SECRET:secret-key-to-change}
            expiration-time: ${JWT_EXPIRATION:30}

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /api/docs
    jwt:
        key: AuthorizationJWT
        scheme: bearer
        format: JWT
        name: Authorization

feign:
    okhttp:
        enabled: true

